apiVersion: v1
kind: Service
metadata:
  labels:
    name: refinecms
  name: refinecms
  namespace: gridvo
spec:
  selector:
    name: refinecms
  type: NodePort
  ports:
     - port: 80
       targetPort: 3666
       nodePort: 31025
