apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: refinecms
  name: refinecms
  namespace: gridvo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: refinecms
    spec:
      containers:
      - name: refinecms
        image: 10.0.3.31:5000/gridvo/refinecms:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_SERVICE_HOST
          value: "mongodb"
